export enum GroupsActions {
  UPDATE_GROUPS = 'UPDATE_GROUPS',
  CREATE_GROUP = 'CREATE_GROUP',
  DELETE_GROUP = 'DELETE_GROUP',
}

export enum DrawerActions {
  SET_DRAWER_CONTENT = 'SET_DRAWER_CONTENT',
  DISCARD_DRAWER_CONTENT = 'DISCARD_DRAWER_CONTENT',
  TOGGLE_DRAWER = 'TOGGLE_DRAWER',
}

export enum ModalsActions {
  OPEN_CREATE_GROUP_MODAL = 'OPEN_CREATE_GROUP_MODAL',
  OPEN_EDIT_GROUP_MODAL = 'OPEN_EDIT_GROUP_MODAL',
  OPEN_CREATE_TASK_MODAL = 'OPEN_CREATE_TASK_MODAL',
  CLOSE_MODALS = 'CLOSE_MODALS',
}

export enum UserActions {
  SET_USER = 'SET_USER',
  SIGN_IN = 'SIGN_IN'
}

export enum TaskAction {
  TRIGGER_TASK = 'TRIGGER_TASK',
}
